### ISSUE TITLE
条件变量案例中通知（condition.notify_one();）了其他线程后为何还要上锁lock.lock();

### ISSUE THREAD

**Issue by Lovegood-1** [wxg250/CPPThreading#1]
在 ComditionVariableSample-video2.cpp  line 80  中 `lock.lock()`  是必要的吗？
 `

void PUpdateStock(StockSafe& safe, condition_variable & condition)
{
	for (int i = 0; i < 5; i++)
	{
		{
			unique_lock<StockSafe> lock(safe);
			SStockBlackBoard& stock = safe.Acquire(lock);
			if (i == 2)
				stock.price = 99;
			else
				stock.price = abs(rand() % 100);

			cout << "Peter >>> " << stock.price << endl;
			if (stock.price > 90)
			{
				lock.unlock();
				cout << "Peter >>> Danny" << endl;
				condition.notify_one();
				this_thread::sleep_for(std::chrono::milliseconds(10));
				lock.lock();  // Is this line necessary?
			}
		}
		std::this_thread::sleep_for(std::chrono::milliseconds(rand() % 10));
	}
}

`

**Comment by jzymessi** [comment]
应该是要的，这边我的理解是当价格达到阈值时，先unlock，再通知，另一个线程处理resource，处理完成之后，再lock上，继续更新price。
